server:
  port: 8503

spring:
  application:
    name: api-gateway


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
  instance:
    prefer-ip-address: 'true'